name: Gerar APK IPTVEC

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Gerar APK
        run: gradle :app:assembleDebug --stacktrace

      - name: Enviar APK
        uses: actions/upload-artifact@v4
        with:
          name: IPTVEC-debug
          path: app/build/outputs/apk/debug/app-debug.apk
